"""empty message

Revision ID: e7759f281e31
Revises: 5505e498b15f
Create Date: 2022-06-12 02:15:33.086420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7759f281e31'
down_revision = '5505e498b15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuario', sa.Column('password', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Usuario', 'password')
    # ### end Alembic commands ###
